runtime: go111

# アクセスがあったときの挙動
handlers:
# 静的ファイル
- url: /js
  static_dir: dist/js
- url: /css
  static_dir: dist/css
- url: /dist/img
  static_dir: img
- url: /dist/manifest.json
  static_dir: dist/manifest.json

- url: /.*
  script: auto


# 一番性能が低い 28インスタンス時間
instance_class: F1

# 待機するインスタンスは最大１つ 3000ms超えたらインスタンス起動
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80
